name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node (volta)
        uses: volta-cli/action@v4
      - name: Install dependencies
        run: npm install
      - name: Lint code style
        run: npm run prettier:check
      - name: Run tests
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Cocogitto
        uses: cocogitto/cocogitto-action@main
        id: release
        with:
          release: true
      - name: Update version
        run: npm version ${{ steps.release.outputs.version }}
      - name: Publish NPM package
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
